"""update category table

Revision ID: 5a55b0a1c9a1
Revises: a03404851a73
Create Date: 2024-12-07 12:31:34.311020

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a55b0a1c9a1'
down_revision: Union[str, None] = 'a03404851a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'emoji',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    # ### end Alembic commands ###
    op.execute('UPDATE category SET emoji = NULL WHERE id = 1')
    op.execute('UPDATE category SET emoji = NULL WHERE id = 2')


def downgrade() -> None:
    op.execute('UPDATE category SET emoji = "" WHERE id = 1')
    op.execute('UPDATE category SET emoji = "👎" WHERE id = 2')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'emoji',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    # ### end Alembic commands ###
