"""create_tables

Revision ID: 910dc124641b
Revises:
Create Date: 2024-11-28 10:57:03.240488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910dc124641b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    category = op.create_table('category',
                               sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                               sa.Column('name', sa.String(length=20), nullable=False),
                               sa.Column('emoji', sa.String(length=20), nullable=False),
                               sa.PrimaryKeyConstraint('id'),
                               sa.UniqueConstraint('emoji'),
                               sa.UniqueConstraint('name')
                               )
    op.create_table('toilet',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('message_id', sa.BigInteger(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('video_file_path', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('message_id')
                    )
    # ### end Alembic commands ###
    op.bulk_insert(category, [
        {'name': 'ノーリアクション', 'emoji': ''},
        {'name': 'おしーしー', 'emoji': '🚽'},
        {'name': 'うんち', 'emoji': '💩'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toilet')
    op.drop_table('category')
    # ### end Alembic commands ###
