"""add column category table

Revision ID: a03404851a73
Revises: 3edb9f950eff
Create Date: 2024-12-05 09:39:40.482316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03404851a73'
down_revision: Union[str, None] = '3edb9f950eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('include_in_summary', sa.Boolean(), server_default=sa.text('True'), nullable=False))
    # ### end Alembic commands ###
    op.execute('UPDATE category SET include_in_summary = FALSE WHERE id = 2')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'include_in_summary')
    # ### end Alembic commands ###
