"""add toilet_category table

Revision ID: aa7ba308dc06
Revises: ba872898c594
Create Date: 2025-04-16 01:41:50.547606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa7ba308dc06'
down_revision: Union[str, None] = 'ba872898c594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new association table
    op.create_table(
        'toilet_category',
        sa.Column('toilet_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['toilet_id'], ['toilet.id']),
        sa.ForeignKeyConstraint(['category_id'], ['category.id']),
        sa.PrimaryKeyConstraint('toilet_id', 'category_id')
    )

    # Bind to connection and insert existing associations
    bind = op.get_bind()
    result = bind.execute(sa.text('SELECT id, category_id FROM toilet WHERE category_id IS NOT NULL'))

    for row in result:
        bind.execute(
            sa.text('INSERT INTO toilet_category (toilet_id, category_id) VALUES (:tid, :cid)'),
            {'tid': row.id, 'cid': row.category_id}
        )

    # Drop the old foreign key and column
    op.drop_constraint('toilet_ibfk_1', 'toilet', type_='foreignkey')
    op.drop_column('toilet', 'category_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toilet', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('toilet_ibfk_1', 'toilet', 'category', ['category_id'], ['id'])
    bind = op.get_bind()
    result = bind.execute(sa.text('SELECT toilet_id, category_id FROM toilet_category'))

    for row in result:
        bind.execute(
            sa.text('UPDATE toilet SET category_id = :cid WHERE id = :tid'),
            {'cid': row.category_id, 'tid': row.toilet_id}
        )
    op.drop_table('toilet_category')
    # ### end Alembic commands ###
