"""add graph_color column

Revision ID: ba872898c594
Revises: b0201cdc740a
Create Date: 2025-01-09 16:43:46.203552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba872898c594'
down_revision: Union[str, None] = 'b0201cdc740a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('graph_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE category SET graph_color = "gray" WHERE id = 1')
    op.execute('UPDATE category SET graph_color = "seagreen" WHERE id = 3')
    op.execute('UPDATE category SET graph_color = "skyblue" WHERE id = 11')
    op.execute('UPDATE category SET graph_color = "sienna" WHERE id = 12')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'graph_color')
    # ### end Alembic commands ###
