name: camenashi_san
services:
  camenashi_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env.prod
    image: camenashi_bot
    container_name: camenashi_bot
    hostname: camenashi_bot
    volumes:
      - type: bind
        source: "../bot"
        target: "/app/bot"
      - type: bind
        source: "../alembic"
        target: "/app/alembic"
    restart: always
    tty: true
