name: camenashi_san
services:
  camenashi_db:
    build:
      context: ./camenashi_db/
    image: camenashi_db
    container_name: camenashi_db
    hostname: camenashi_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
